In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_table("total_promoter_histonesignal.txt",header=None)
df.columns = ["chr", "start", "end", "wt-k27ac_1", "wt-k27ac_2",'wt-4me3_1','wt-4me3_2', "wt-input_1", "wt-input_2", "pi-k27ac_1", "pi-k27ac_2",'pi-4me3_1','pi-4me3_2',"pi-input_1", "pi-input_2","DEGs"]
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-4me3_1,pi-4me3_2,pi-input_1,pi-input_2,DEGs
0,chr11,9010000,9020000,1024.0,1180.0,2425.0,2028.0,85.0,81.0,1019.0,1448.0,706.0,2723.0,38.0,50.0,merge
1,chr14,56540000,56550000,4878.0,6357.0,5525.0,4589.0,411.0,391.0,4724.0,7779.0,1373.0,6140.0,176.0,244.0,merge
2,chr13,89700000,89710000,4753.0,4102.0,1335.0,1387.0,282.0,284.0,2384.0,3436.0,1093.0,5720.0,96.0,77.0,merge
3,chr3,46740000,46750000,502.0,647.0,181.0,179.0,83.0,104.0,1165.0,2073.0,454.0,2445.0,100.0,99.0,merge
4,chr4,111340000,111350000,2082.0,3277.0,5249.0,4624.0,309.0,274.0,3378.0,4538.0,2525.0,9339.0,112.0,92.0,merge

In [3]:
#calibrate depth
df["wt-k27ac_1nor"] = df["wt-k27ac_1"]/47
df["wt-k27ac_2nor"] = df["wt-k27ac_2"]/53
df["wt-4me3_1nor"] = df["wt-4me3_1"]/37
df["wt-4me3_2nor"] = df["wt-4me3_2"]/34
df["wt-igg_1nor"] = df["wt-input_1"]/10
df["wt-igg_2nor"] = df["wt-input_2"]/10
df["pi-k27ac_1nor"] = df["pi-k27ac_1"]/38
df["pi-k27ac_2nor"] = df["pi-k27ac_2"]/59
df["pi-4me3_1nor"] = df["pi-4me3_1"]/13
df["pi-4me3_2nor"] = df["pi-4me3_2"]/58
df["pi-igg_1nor"] = df["pi-input_1"]/8
df["pi-igg_2nor"] = df["pi-input_2"]/9
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-input_1,wt-input_2,pi-k27ac_1,...,wt-4me3_1nor,wt-4me3_2nor,wt-igg_1nor,wt-igg_2nor,pi-k27ac_1nor,pi-k27ac_2nor,pi-4me3_1nor,pi-4me3_2nor,pi-igg_1nor,pi-igg_2nor
0,chr11,9010000,9020000,1024.0,1180.0,2425.0,2028.0,85.0,81.0,1019.0,...,65.540541,59.647059,8.5,8.1,26.815789,24.542373,54.307692,46.948276,4.75,5.555556
1,chr14,56540000,56550000,4878.0,6357.0,5525.0,4589.0,411.0,391.0,4724.0,...,149.324324,134.970588,41.1,39.1,124.315789,131.847458,105.615385,105.862069,22.00,27.111111
2,chr13,89700000,89710000,4753.0,4102.0,1335.0,1387.0,282.0,284.0,2384.0,...,36.081081,40.794118,28.2,28.4,62.736842,58.237288,84.076923,98.620690,12.00,8.555556
3,chr3,46740000,46750000,502.0,647.0,181.0,179.0,83.0,104.0,1165.0,...,4.891892,5.264706,8.3,10.4,30.657895,35.135593,34.923077,42.155172,12.50,11.000000
4,chr4,111340000,111350000,2082.0,3277.0,5249.0,4624.0,309.0,274.0,3378.0,...,141.864865,136.000000,30.9,27.4,88.894737,76.915254,194.230769,161.017241,14.00,10.222222

In [4]:
df['wt-k27ac_mean'] = df[['wt-k27ac_1nor', 'wt-k27ac_2nor']].mean(axis=1)
df['wt-4me3_mean'] = df[['wt-4me3_1nor', 'wt-4me3_2nor']].mean(axis=1)
df['wt-igg_mean'] = df[['wt-igg_1nor', 'wt-igg_2nor']].mean(axis=1)

In [5]:
df['pi-k27ac_mean'] = df[['pi-k27ac_1nor', 'pi-k27ac_2nor']].mean(axis=1)
df['pi-4me3_mean'] = df[['pi-4me3_1nor', 'pi-4me3_2nor']].mean(axis=1)
df['pi-igg_mean'] = df[['pi-igg_1nor', 'pi-igg_2nor']].mean(axis=1)

In [6]:
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-input_1,wt-input_2,pi-k27ac_1,...,pi-4me3_1nor,pi-4me3_2nor,pi-igg_1nor,pi-igg_2nor,wt-k27ac_mean,wt-4me3_mean,wt-igg_mean,pi-k27ac_mean,pi-4me3_mean,pi-igg_mean
0,chr11,9010000,9020000,1024.0,1180.0,2425.0,2028.0,85.0,81.0,1019.0,...,54.307692,46.948276,4.75,5.555556,22.025692,62.593800,8.30,25.679081,50.627984,5.152778
1,chr14,56540000,56550000,4878.0,6357.0,5525.0,4589.0,411.0,391.0,4724.0,...,105.615385,105.862069,22.00,27.111111,111.865315,142.147456,40.10,128.081624,105.738727,24.555556
2,chr13,89700000,89710000,4753.0,4102.0,1335.0,1387.0,282.0,284.0,2384.0,...,84.076923,98.620690,12.00,8.555556,89.261943,38.437599,28.30,60.487065,91.348806,10.277778
3,chr3,46740000,46750000,502.0,647.0,181.0,179.0,83.0,104.0,1165.0,...,34.923077,42.155172,12.50,11.000000,11.444199,5.078299,9.35,32.896744,38.539125,11.750000
4,chr4,111340000,111350000,2082.0,3277.0,5249.0,4624.0,309.0,274.0,3378.0,...,194.230769,161.017241,14.00,10.222222,53.064031,138.932432,29.15,82.904996,177.624005,12.111111

In [7]:
df["wt-k27ac_change"] = np.log2((df["wt-k27ac_mean"] + 1e-3)/(df["wt-igg_mean"] + 1e-3))
df["wt-4me3_change"] = np.log2((df["wt-4me3_mean"] + 1e-3)/(df["wt-igg_mean"] + 1e-3))
df["pi-k27ac_change"] = np.log2((df["pi-k27ac_mean"] + 1e-3)/(df["pi-igg_mean"] + 1e-3))
df["pi-4me3_change"] = np.log2((df["pi-4me3_mean"] + 1e-3)/(df["pi-igg_mean"] + 1e-3))
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-input_1,wt-input_2,pi-k27ac_1,...,wt-k27ac_mean,wt-4me3_mean,wt-igg_mean,pi-k27ac_mean,pi-4me3_mean,pi-igg_mean,wt-k27ac_change,wt-4me3_change,pi-k27ac_change,pi-4me3_change
0,chr11,9010000,9020000,1024.0,1180.0,2425.0,2028.0,85.0,81.0,1019.0,...,22.025692,62.593800,8.30,25.679081,50.627984,5.152778,1.407896,2.914686,2.316948,3.296261
1,chr14,56540000,56550000,4878.0,6357.0,5525.0,4589.0,411.0,391.0,4724.0,...,111.865315,142.147456,40.10,128.081624,105.738727,24.555556,1.480066,1.825688,2.382895,2.106337
2,chr13,89700000,89710000,4753.0,4102.0,1335.0,1387.0,282.0,284.0,2384.0,...,89.261943,38.437599,28.30,60.487065,91.348806,10.277778,1.657208,0.441703,2.556982,3.151733
3,chr3,46740000,46750000,502.0,647.0,181.0,179.0,83.0,104.0,1165.0,...,11.444199,5.078299,9.35,32.896744,38.539125,11.750000,0.291550,-0.880491,1.485205,1.713578
4,chr4,111340000,111350000,2082.0,3277.0,5249.0,4624.0,309.0,274.0,3378.0,...,53.064031,138.932432,29.15,82.904996,177.624005,12.111111,0.864216,2.252777,2.775026,3.874312

In [8]:
df.loc[df['wt-k27ac_change'] < 0, 'wt-k27ac_change'] = 0
df.loc[df['wt-4me3_change'] < 0, 'wt-4me3_change'] = 0
df.loc[df['pi-k27ac_change'] < 0, 'pi-k27ac_change'] = 0
df.loc[df['pi-4me3_change'] < 0, 'pi-4me3_change'] = 0
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-input_1,wt-input_2,pi-k27ac_1,...,wt-k27ac_mean,wt-4me3_mean,wt-igg_mean,pi-k27ac_mean,pi-4me3_mean,pi-igg_mean,wt-k27ac_change,wt-4me3_change,pi-k27ac_change,pi-4me3_change
0,chr11,9010000,9020000,1024.0,1180.0,2425.0,2028.0,85.0,81.0,1019.0,...,22.025692,62.593800,8.30,25.679081,50.627984,5.152778,1.407896,2.914686,2.316948,3.296261
1,chr14,56540000,56550000,4878.0,6357.0,5525.0,4589.0,411.0,391.0,4724.0,...,111.865315,142.147456,40.10,128.081624,105.738727,24.555556,1.480066,1.825688,2.382895,2.106337
2,chr13,89700000,89710000,4753.0,4102.0,1335.0,1387.0,282.0,284.0,2384.0,...,89.261943,38.437599,28.30,60.487065,91.348806,10.277778,1.657208,0.441703,2.556982,3.151733
3,chr3,46740000,46750000,502.0,647.0,181.0,179.0,83.0,104.0,1165.0,...,11.444199,5.078299,9.35,32.896744,38.539125,11.750000,0.291550,0.000000,1.485205,1.713578
4,chr4,111340000,111350000,2082.0,3277.0,5249.0,4624.0,309.0,274.0,3378.0,...,53.064031,138.932432,29.15,82.904996,177.624005,12.111111,0.864216,2.252777,2.775026,3.874312

In [9]:
h3k27ac = df[["chr","start","end","wt-k27ac_change","pi-k27ac_change","DEGs"]] 
h3k27ac.head()
h3k27ac.to_csv("promoter_h3k27ac_change.txt", sep="\t", index=False)

In [10]:
h3k4me3 = df[["chr","start","end","wt-4me3_change","pi-4me3_change","DEGs"]] 
h3k4me3.head()
h3k4me3.to_csv("promoter_h3k4me3_change.txt", sep="\t", index=False)