In [8]:
import pandas as pd
import numpy as np
df = pd.read_csv("all_sgRNA.txt", sep="\t")
df.columns = ["sgRNA","GeneID","PigGeCKO cells_read1","PigGeCKO cells_read2","PigGeCKO cells_read1_norm","PigGeCKO cells_read2_norm","average(PigGeCKO cells)","read1","read2","read1_norm","read2_norm","average","Fold_change","log2(Fold_change)"]
df['GeneID'] = df['GeneID'].str.lstrip(" ")
df

,sgRNA,GeneID,PigGeCKO cells_read1,PigGeCKO cells_read2,PigGeCKO cells_read1_norm,PigGeCKO cells_read2_norm,average(PigGeCKO cells),read1,read2,read1_norm,read2_norm,average,Fold_change,log2(Fold_change)
0,ALDBSSCT0000001907_24_53_m,SUPT20H,13,11,13.679934,11.507493,12.593713,1,1,1.414214,1.500000,1.457107,0.115701123,-3.111525227
1,ALDBSSCT0000001907_35_64_m,SUPT20H,3,12,3.156908,12.553629,7.855268,0,0,0.000000,0.000000,0.000000,0,#NUM!
2,ALDBSSCT0000001907_36_65_p,SUPT20H,0,0,0.000000,0.000000,0.000000,0,0,0.000000,0.000000,0.000000,#DIV/0!,#DIV/0!
3,ALDBSSCT0000002434_129_158_p,MYO19,8,6,8.418421,6.276814,7.347618,0,0,0.000000,0.000000,0.000000,0,#NUM!
4,ALDBSSCT0000002434_133_162_m,MYO19,30,26,31.569077,27.199529,29.384303,0,0,0.000000,0.000000,0.000000,0,#NUM!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,ENSSSCG00000030680_2_142073660_142073689_p,TCF7,24,35,25.255262,36.614751,30.935007,2128,2573,3009.446461,3638.771496,3324.108978,107.4546073,6.747583532
813,ENSSSCG00000030680_2_142073660_142073689_p,TCF7,24,35,25.255262,36.614751,30.935007,2237,2616,3163.595739,3699.582679,3431.589209,110.9289958,6.793492712
814,ENSSSCG00000030680_2_142073660_142073689_p,TCF7,24,35,25.255262,36.614751,30.935007,840,892,1187.939392,1338.000000,1262.969696,40.82655341,5.351435875
815,ENSSSCG00000030680_2_142073768_142073797_p,TCF7,59,60,62.085852,62.768145,62.426999,0,0,0.000000,0.000000,0.000000,0,#NUM!
816,ENSSSCG00000030680_2_142073768_142073797_p,TCF7,59,60,62.085852,62.768145,62.426999,1,0,1.414214,0.000000,0.707107,0.011326939,-6.464098198

In [18]:
df = df[df['log2(Fold_change)'].str.match("-?\d+.*")]
df['log2(Fold_change)'] = df['log2(Fold_change)'].astype(np.float64)

In [22]:
df[df["GeneID"] == "ANPEP"]

,sgRNA,GeneID,PigGeCKO cells_read1,PigGeCKO cells_read2,PigGeCKO cells_read1_norm,PigGeCKO cells_read2_norm,average(PigGeCKO cells),read1,read2,read1_norm,read2_norm,average,Fold_change,log2(Fold_change)
91,ENSSSCG00000001849_7_60254627_60254656_m,ANPEP,41,40,43.144406,41.845430,42.494918,1052776,1219191,1.488850e+06,1.724196e+06,1.606523e+06,37805.06834,15.206292
92,ENSSSCG00000001849_7_60254627_60254656_m,ANPEP,41,40,43.144406,41.845430,42.494918,1143091,1337380,1.616575e+06,2.006070e+06,1.811322e+06,42624.44759,15.379394
93,ENSSSCG00000001849_7_60254627_60254656_m,ANPEP,41,40,43.144406,41.845430,42.494918,1369759,1578139,1.937132e+06,2.231826e+06,2.084479e+06,49052.42257,15.582037
94,ENSSSCG00000001849_7_60254653_60254682_p,ANPEP,6,6,6.313815,6.276814,6.295315,7534,8749,1.065468e+04,1.237295e+04,1.151382e+04,1828.950538,10.836800
95,ENSSSCG00000001849_7_60254653_60254682_p,ANPEP,6,6,6.313815,6.276814,6.295315,8468,9995,1.197556e+04,1.499250e+04,1.348403e+04,2141.915101,11.064686
96,ENSSSCG00000001849_7_60254653_60254682_p,ANPEP,6,6,6.313815,6.276814,6.295315,9459,11333,1.337705e+04,1.602728e+04,1.470216e+04,2335.413596,11.189462
97,ENSSSCG00000001849_7_60254813_60254842_m,ANPEP,8,15,8.418421,15.692036,12.055228,394,431,5.572001e+02,6.465000e+02,6.018501e+02,49.92440217,5.641673
98,ENSSSCG00000001849_7_60254813_60254842_m,ANPEP,8,15,8.418421,15.692036,12.055228,431,453,6.095260e+02,6.406387e+02,6.250824e+02,51.85155958,5.696315
99,ENSSSCG00000001849_7_60254813_60254842_m,ANPEP,8,15,8.418421,15.692036,12.055228,465,600,6.576093e+02,8.485281e+02,7.530687e+02,62.46822505,5.965051

In [23]:
idx = df.groupby(['GeneID'])['log2(Fold_change)'].transform(max) == df['log2(Fold_change)']

In [24]:
df_test = df[idx]
df_test

,sgRNA,GeneID,PigGeCKO cells_read1,PigGeCKO cells_read2,PigGeCKO cells_read1_norm,PigGeCKO cells_read2_norm,average(PigGeCKO cells),read1,read2,read1_norm,read2_norm,average,Fold_change,log2(Fold_change)
14,ALDBSSCT0000002835_76_105_p,HSPBAP1,92,90,96.811837,94.152217,95.482027,284,336,401.636652,475.175757,438.406204,4.591504986,2.198967
43,ENSSSCG00000000386_5_23013291_23013320_m,ANKRD52,63,74,66.295063,77.414045,71.854554,353,465,499.217387,657.609307,578.413347,8.049779947,3.008949
51,ENSSSCG00000000456_5_26860253_26860282_m,SLC16A7,39,50,41.039801,52.306787,46.673294,625,705,883.883477,997.020561,940.452019,20.14968173,4.332685
57,ENSSSCG00000000760_5_70973192_70973221_p,LRTM2,17,21,17.889144,21.968851,19.928997,26,27,36.769553,38.183766,37.476659,1.880509034,0.911123
62,ENSSSCG00000000941_5_104179267_104179296_p,CCDC59,113,85,118.910192,88.921538,103.915865,73,101,103.237590,142.835570,123.036580,1.184001884,0.243671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,ENSSSCG00000028733_8_41671949_41671978_p,USP46,37,38,38.935195,39.753158,39.344177,1,1,1.414214,1.414214,1.414214,0.035944673,-4.798078
785,ENSSSCG00000029249_5_108177927_108177956_p,NAV3,56,38,58.928944,39.753158,49.341051,207,262,292.742207,370.523953,331.633080,6.721240646,2.748728
791,ENSSSCG00000029874_12_40615250_40615279_m,DUSP14,50,76,52.615129,79.506317,66.060723,65,91,91.923882,128.693434,110.308658,1.669807006,0.739681
805,ENSSSCG00000030480_13_211218464_211218493_p,DYRK1A,135,126,142.060848,131.813104,136.936976,57585,68827,81437.487990,97336.076860,89386.782420,652.758553,9.350406
813,ENSSSCG00000030680_2_142073660_142073689_p,TCF7,24,35,25.255262,36.614751,30.935007,2237,2616,3163.595739,3699.582679,3431.589209,110.9289958,6.793493

In [25]:
df_test[df_test["GeneID"] == "ANPEP"]

,sgRNA,GeneID,PigGeCKO cells_read1,PigGeCKO cells_read2,PigGeCKO cells_read1_norm,PigGeCKO cells_read2_norm,average(PigGeCKO cells),read1,read2,read1_norm,read2_norm,average,Fold_change,log2(Fold_change)
93,ENSSSCG00000001849_7_60254627_60254656_m,ANPEP,41,40,43.144406,41.84543,42.494918,1369759,1578139,1937131.755,2231825.577,2084478.666,49052.42257,15.582037

In [35]:
df_seq = pd.read_csv("/public/home/luzhang/08.TGEV/00.data/CRISPR_results/pig_lib_v1_85674.txt", sep="\t", header =None)
df_seq.columns = ["sgRNA", "seq", "GeneID"]
df_seq

,sgRNA,seq,GeneID
0,ENSSSCG00000008891_8_55661053_55661082_p,AATCCAGTGACTCTCATCCGGGG,MARCH1
1,ENSSSCG00000008891_8_55660919_55660948_p,CCTTTGGACCCCAAATCCACCGG,MARCH1
2,ENSSSCG00000008891_8_55660927_55660956_p,CCCCAAATCCACCGGATCGAGGG,MARCH1
3,ENSSSCG00000013601_2_71232281_71232310_p,TGAGCCCCACGGCTTCCAGCCGG,MARCH2
4,ENSSSCG00000013601_2_71233903_71233932_p,TCTCCACTGCAAACTCCGTGTGG,MARCH2
...,...,...,...
85669,PVRL2-sgRlib-2,TGACCTCCTGGGTCTCGGCG,PVRL2-sgRlib-2
85670,PVRL2-sgRlib-3,TGTCAAGATCACCTGCAGAG,PVRL2-sgRlib-3
85671,ANPEP-sgRlib-1,GCAACAGCGTTGTGGGTAGG,ANPEP-sgRlib-1
85672,ANPEP-sgRlib-2,ACCCTACCTCACTCCCAACGG,ANPEP-sgRlib-2
85673,ANPEP-sgRlib-3,CAGAGCGATGATGGTGGCCA,ANPEP-sgRlib-3

In [36]:
df_out = df_seq.merge(df_test, on="sgRNA")

In [37]:
df_out.to_csv("TGEV_keyGene_sgRNA.txt", index=None, sep="\t")