In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_table("scores_per_100kb_new.tab")
df.columns = ["chr", "start", "end", "wt-k27ac_1", "wt-k27ac_2",'wt-4me3_1','wt-4me3_2','wt-27me3_1','wt-27me3_2', "wt-input_1", "wt-input_2", "pi-k27ac_1", "pi-k27ac_2",'pi-4me3_1','pi-4me3_2','pi-27me3_1','pi-27me3_2',"pi-input_1", "pi-input_2"]
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-4me3_1,pi-4me3_2,pi-27me3_1,pi-27me3_2,pi-input_1,pi-input_2
0,chr1,0,100000,3997.0,5632.0,4082.0,3658.0,5200.0,6615.0,905.0,904.0,3602.0,5343.0,1282.0,6499.0,2677.0,4612.0,598.0,785.0
1,chr1,100000,200000,2782.0,3883.0,2458.0,2165.0,1701.0,1984.0,710.0,724.0,3182.0,4987.0,720.0,3214.0,791.0,1395.0,601.0,701.0
2,chr1,200000,300000,1054.0,1907.0,951.0,867.0,8491.0,11878.0,621.0,670.0,1807.0,2837.0,326.0,1569.0,6931.0,11227.0,632.0,709.0
3,chr1,300000,400000,1222.0,2121.0,832.0,798.0,7396.0,9533.0,659.0,614.0,1484.0,2311.0,295.0,1264.0,6478.0,11045.0,632.0,656.0
4,chr1,400000,500000,2276.0,4406.0,1317.0,1177.0,5129.0,6626.0,824.0,794.0,2360.0,3766.0,333.0,1650.0,4040.0,7494.0,578.0,721.0

In [33]:
#h3k4me3_R1,h3k4me3_R2
#41,285,688 38,983,472

### normalization of sequence depth

In [3]:
df["wt-k27ac_1nor"] = df["wt-k27ac_1"]/47
df["wt-k27ac_2nor"] = df["wt-k27ac_2"]/53
df["wt-4me3_1nor"] = df["wt-4me3_1"]/37
df["wt-4me3_2nor"] = df["wt-4me3_2"]/34
df["wt-k27me3_1nor"] = df["wt-27me3_1"]/63
df["wt-k27me3_2nor"] = df["wt-27me3_2"]/73
df["wt-igg_1nor"] = df["wt-input_1"]/10
df["wt-igg_2nor"] = df["wt-input_2"]/10
df["pi-k27ac_1nor"] = df["pi-k27ac_1"]/38
df["pi-k27ac_2nor"] = df["pi-k27ac_2"]/59
df["pi-4me3_1nor"] = df["pi-4me3_1"]/13
df["pi-4me3_2nor"] = df["pi-4me3_2"]/58
df["pi-k27me3_1nor"] = df["pi-27me3_1"]/26
df["pi-k27me3_2nor"] = df["pi-27me3_2"]/46
df["pi-igg_1nor"] = df["pi-input_1"]/8
df["pi-igg_2nor"] = df["pi-input_2"]/9
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,...,wt-igg_1nor,wt-igg_2nor,pi-k27ac_1nor,pi-k27ac_2nor,pi-4me3_1nor,pi-4me3_2nor,pi-k27me3_1nor,pi-k27me3_2nor,pi-igg_1nor,pi-igg_2nor
0,chr1,0,100000,3997.0,5632.0,4082.0,3658.0,5200.0,6615.0,905.0,...,90.5,90.4,94.789474,90.559322,98.615385,112.051724,102.961538,100.260870,74.750,87.222222
1,chr1,100000,200000,2782.0,3883.0,2458.0,2165.0,1701.0,1984.0,710.0,...,71.0,72.4,83.736842,84.525424,55.384615,55.413793,30.423077,30.326087,75.125,77.888889
2,chr1,200000,300000,1054.0,1907.0,951.0,867.0,8491.0,11878.0,621.0,...,62.1,67.0,47.552632,48.084746,25.076923,27.051724,266.576923,244.065217,79.000,78.777778
3,chr1,300000,400000,1222.0,2121.0,832.0,798.0,7396.0,9533.0,659.0,...,65.9,61.4,39.052632,39.169492,22.692308,21.793103,249.153846,240.108696,79.000,72.888889
4,chr1,400000,500000,2276.0,4406.0,1317.0,1177.0,5129.0,6626.0,824.0,...,82.4,79.4,62.105263,63.830508,25.615385,28.448276,155.384615,162.913043,72.250,80.111111

In [4]:
df['wt-k27ac_mean'] = df[['wt-k27ac_1nor', 'wt-k27ac_2nor']].mean(axis=1)
df['wt-4me3_mean'] = df[['wt-4me3_1nor', 'wt-4me3_2nor']].mean(axis=1)
df['wt-k27me3_mean'] = df[['wt-k27me3_1nor', 'wt-k27me3_2nor']].mean(axis=1)
df['wt-igg_mean'] = df[['wt-igg_1nor', 'wt-igg_2nor']].mean(axis=1)

In [5]:
df['pi-k27ac_mean'] = df[['pi-k27ac_1nor', 'pi-k27ac_2nor']].mean(axis=1)
df['pi-4me3_mean'] = df[['pi-4me3_1nor', 'pi-4me3_2nor']].mean(axis=1)
df['pi-k27me3_mean'] = df[['pi-k27me3_1nor', 'pi-k27me3_2nor']].mean(axis=1)
df['pi-igg_mean'] = df[['pi-igg_1nor', 'pi-igg_2nor']].mean(axis=1)

In [22]:
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,...,pi-igg_1nor,pi-igg_2nor,wt-k27ac_mean,wt-4me3_mean,wt-k27me3_mean,wt-igg_mean,pi-k27ac_mean,pi-4me3_mean,pi-k27me3_mean,pi-igg_mean
0,chr1,0,100000,3997.0,5632.0,4082.0,3658.0,5200.0,6615.0,905.0,...,74.750,87.222222,95.653352,108.956280,86.578060,90.45,92.674398,105.333554,101.611204,80.986111
1,chr1,100000,200000,2782.0,3883.0,2458.0,2165.0,1701.0,1984.0,710.0,...,75.125,77.888889,66.227820,65.054452,27.089041,71.70,84.131133,55.399204,30.374582,76.506944
2,chr1,200000,300000,1054.0,1907.0,951.0,867.0,8491.0,11878.0,621.0,...,79.000,78.777778,29.203332,25.601351,148.745053,64.55,47.818689,26.064324,255.321070,78.888889
3,chr1,300000,400000,1222.0,2121.0,832.0,798.0,7396.0,9533.0,659.0,...,79.000,72.888889,33.009434,22.978537,123.992933,63.65,39.111062,22.242706,244.631271,75.944444
4,chr1,400000,500000,2276.0,4406.0,1317.0,1177.0,5129.0,6626.0,824.0,...,72.250,80.111111,65.778804,35.106121,86.089911,80.90,62.967886,27.031830,159.148829,76.180556

In [6]:
df["wt-k27ac_change"] = df["wt-k27ac_mean"]-df["wt-igg_mean"]
df["wt-4me3_change"] = df["wt-4me3_mean"]-df["wt-igg_mean"]
df["wt-k27me3_change"] = df["wt-k27me3_mean"]-df["wt-igg_mean"]
df["pi-k27ac_change"] = df["pi-k27ac_mean"]-df["pi-igg_mean"]
df["pi-4me3_change"] = df["pi-4me3_mean"]-df["pi-igg_mean"]
df["pi-k27me3_change"] = df["pi-k27me3_mean"]-df["pi-igg_mean"]
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,...,pi-k27ac_mean,pi-4me3_mean,pi-k27me3_mean,pi-igg_mean,wt-k27ac_change,wt-4me3_change,wt-k27me3_change,pi-k27ac_change,pi-4me3_change,pi-k27me3_change
0,chr1,0,100000,3997.0,5632.0,4082.0,3658.0,5200.0,6615.0,905.0,...,92.674398,105.333554,101.611204,80.986111,5.203352,18.506280,-3.871940,11.688287,24.347443,20.625093
1,chr1,100000,200000,2782.0,3883.0,2458.0,2165.0,1701.0,1984.0,710.0,...,84.131133,55.399204,30.374582,76.506944,-5.472180,-6.645548,-44.610959,7.624188,-21.107740,-46.132363
2,chr1,200000,300000,1054.0,1907.0,951.0,867.0,8491.0,11878.0,621.0,...,47.818689,26.064324,255.321070,78.888889,-35.346668,-38.948649,84.195053,-31.070200,-52.824565,176.432181
3,chr1,300000,400000,1222.0,2121.0,832.0,798.0,7396.0,9533.0,659.0,...,39.111062,22.242706,244.631271,75.944444,-30.640566,-40.671463,60.342933,-36.833383,-53.701739,168.686826
4,chr1,400000,500000,2276.0,4406.0,1317.0,1177.0,5129.0,6626.0,824.0,...,62.967886,27.031830,159.148829,76.180556,-15.121196,-45.793879,5.189911,-13.212670,-49.148725,82.968274

In [28]:
h3k27ac = df[["chr","start","end","wt-k27ac_change","pi-k27ac_change"]] 
h3k27ac.head()
h3k27ac.to_csv("h3k27ac_change.tab", sep="\t", index=False)

In [7]:
h3k4me3 = df[["chr","start","end","wt-4me3_change","pi-4me3_change"]] 
h3k4me3.head()
h3k4me3.to_csv("h3k4me3_change.tab", sep="\t", index=False)

In [30]:
h3k27me3 = df[["chr","start","end","wt-k27me3_change","pi-k27me3_change"]] 
h3k27me3.head()
h3k27me3.to_csv("h3k27me3_change.tab", sep="\t", index=False)

In [8]:
h3k4me3 = pd.read_table("h3k4me3_change.tab")
h3k4me3.shape

(24342, 5)

In [10]:
h3k4me3[['wt-4me3_change', 'pi-4me3_change']] = h3k4me3[['wt-4me3_change', 'pi-4me3_change']].applymap(lambda x: 1 if x < 0 else x)
h3k4me3[['wt-4me3_change', 'pi-4me3_change']] = h3k4me3[['wt-4me3_change', 'pi-4me3_change']].apply(np.log)
h3k4me3.to_csv("h3k4me3_log.txt", sep="\t", index=False)

In [11]:
h3k27ac = pd.read_table("h3k27ac_change.tab")
h3k27ac.shape

(24342, 5)

In [8]:
negative_rows = h3k27ac[(h3k27ac['wt-k27ac_change'] < 0) & (h3k27ac['pi-k27ac_change'] < 0)]
negative_rows.shape

(15247, 5)

In [12]:
h3k27ac[['wt-k27ac_change', 'pi-k27ac_change']] = h3k27ac[['wt-k27ac_change', 'pi-k27ac_change']].applymap(lambda x: 1 if x < 0 else x)
h3k27ac.head()

    chr   start     end  wt-k27ac_change  pi-k27ac_change
0  chr1       0  100000         5.203352        11.688287
1  chr1  100000  200000         1.000000         7.624188
2  chr1  200000  300000         1.000000         1.000000
3  chr1  300000  400000         1.000000         1.000000
4  chr1  400000  500000         1.000000         1.000000

In [13]:
h3k27ac[['wt-k27ac_change', 'pi-k27ac_change']] = h3k27ac[['wt-k27ac_change', 'pi-k27ac_change']].apply(np.log)
h3k27ac.head()

    chr   start     end  wt-k27ac_change  pi-k27ac_change
0  chr1       0  100000         1.649303         2.458587
1  chr1  100000  200000         0.000000         2.031326
2  chr1  200000  300000         0.000000         0.000000
3  chr1  300000  400000         0.000000         0.000000
4  chr1  400000  500000         0.000000         0.000000

In [15]:
h3k27ac.to_csv("h3k27ac_log.txt", sep="\t", index=False)

In [16]:
h3k27me3 = pd.read_table("h3k27me3_change.tab")
h3k27me3[['wt-k27me3_change', 'pi-k27me3_change']] = h3k27me3[['wt-k27me3_change', 'pi-k27me3_change']].applymap(lambda x: 1 if x < 0 else x)
h3k27me3[['wt-k27me3_change', 'pi-k27me3_change']] = h3k27me3[['wt-k27me3_change', 'pi-k27me3_change']].apply(np.log)
h3k27me3.to_csv("h3k27me3_log.txt", sep="\t", index=False)