In [22]:
import pandas as pd

In [23]:
df = pd.read_table("k4me3_peakReadcount.txt")
df.columns = ["chr", "start", "end", "k4me3_1", "k4me3_2", "input_1", "input_2"]

In [24]:
#h3k4me3_R1,h3k4me3_R2
#41,285,688 38,983,472

### normalization of sequence depth

In [25]:
df["k4me3_1nor"] = df["k4me3_1"]/41
df["k4me3_2nor"] = df["k4me3_1"]/38
df["igg_1nor"] = df["input_1"]/7
df["igg_2nor"] = df["input_2"]/5
df

,chr,start,end,k4me3_1,k4me3_2,input_1,input_2,k4me3_1nor,k4me3_2nor,igg_1nor,igg_2nor
0,10,10577422,10577881,123.0,98.0,4.0,1.0,3.000000,3.236842,0.571429,0.2
1,9,107272710,107274755,4719.0,4201.0,77.0,72.0,115.097561,124.184211,11.000000,14.4
2,9,107292327,107293038,302.0,314.0,0.0,3.0,7.365854,7.947368,0.000000,0.6
3,14,85683768,85684531,118.0,112.0,5.0,13.0,2.878049,3.105263,0.714286,2.6
4,7,112895970,112897740,2554.0,2385.0,54.0,88.0,62.292683,67.210526,7.714286,17.6
...,...,...,...,...,...,...,...,...,...,...,...
16205,6,3136505,3139006,5464.0,6003.0,47.0,54.0,133.268293,143.789474,6.714286,10.8
16206,6,3180474,3182531,2302.0,2577.0,51.0,73.0,56.146341,60.578947,7.285714,14.6
16207,13,31204041,31205847,3772.0,3550.0,91.0,127.0,92.000000,99.263158,13.000000,25.4
16208,13,31255461,31256397,1235.0,1289.0,82.0,93.0,30.121951,32.500000,11.714286,18.6
16209,1,266527441,266529081,1234.0,1148.0,11.0,8.0,30.097561,32.473684,1.571429,1.6

In [26]:
def mean_of_cols(row):
        return row[["k4me3_1nor","k4me3_2nor"]].mean()

    

df["k4me3_mean"] = df.apply(mean_of_cols, axis=1)

In [27]:
def mean_of_cols(row):
        return row[["igg_1nor","igg_2nor"]].mean()

    

df["igg_mean"] = df.apply(mean_of_cols, axis=1)

In [28]:
df

,chr,start,end,k4me3_1,k4me3_2,input_1,input_2,k4me3_1nor,k4me3_2nor,igg_1nor,igg_2nor,k4me3_mean,igg_mean
0,10,10577422,10577881,123.0,98.0,4.0,1.0,3.000000,3.236842,0.571429,0.2,3.118421,0.385714
1,9,107272710,107274755,4719.0,4201.0,77.0,72.0,115.097561,124.184211,11.000000,14.4,119.640886,12.700000
2,9,107292327,107293038,302.0,314.0,0.0,3.0,7.365854,7.947368,0.000000,0.6,7.656611,0.300000
3,14,85683768,85684531,118.0,112.0,5.0,13.0,2.878049,3.105263,0.714286,2.6,2.991656,1.657143
4,7,112895970,112897740,2554.0,2385.0,54.0,88.0,62.292683,67.210526,7.714286,17.6,64.751605,12.657143
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16205,6,3136505,3139006,5464.0,6003.0,47.0,54.0,133.268293,143.789474,6.714286,10.8,138.528883,8.757143
16206,6,3180474,3182531,2302.0,2577.0,51.0,73.0,56.146341,60.578947,7.285714,14.6,58.362644,10.942857
16207,13,31204041,31205847,3772.0,3550.0,91.0,127.0,92.000000,99.263158,13.000000,25.4,95.631579,19.200000
16208,13,31255461,31256397,1235.0,1289.0,82.0,93.0,30.121951,32.500000,11.714286,18.6,31.310976,15.157143
16209,1,266527441,266529081,1234.0,1148.0,11.0,8.0,30.097561,32.473684,1.571429,1.6,31.285623,1.585714

In [31]:
df["change"] = df["k4me3_mean"]-df["igg_mean"]
df["foldchange"] = df["k4me3_mean"]/df["igg_mean"]
df

,chr,start,end,k4me3_1,k4me3_2,input_1,input_2,k4me3_1nor,k4me3_2nor,igg_1nor,igg_2nor,k4me3_mean,igg_mean,change,foldchange
0,10,10577422,10577881,123.0,98.0,4.0,1.0,3.000000,3.236842,0.571429,0.2,3.118421,0.385714,2.732707,8.084795
1,9,107272710,107274755,4719.0,4201.0,77.0,72.0,115.097561,124.184211,11.000000,14.4,119.640886,12.700000,106.940886,9.420542
2,9,107292327,107293038,302.0,314.0,0.0,3.0,7.365854,7.947368,0.000000,0.6,7.656611,0.300000,7.356611,25.522037
3,14,85683768,85684531,118.0,112.0,5.0,13.0,2.878049,3.105263,0.714286,2.6,2.991656,1.657143,1.334513,1.805310
4,7,112895970,112897740,2554.0,2385.0,54.0,88.0,62.292683,67.210526,7.714286,17.6,64.751605,12.657143,52.094462,5.115815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16205,6,3136505,3139006,5464.0,6003.0,47.0,54.0,133.268293,143.789474,6.714286,10.8,138.528883,8.757143,129.771740,15.818959
16206,6,3180474,3182531,2302.0,2577.0,51.0,73.0,56.146341,60.578947,7.285714,14.6,58.362644,10.942857,47.419787,5.333401
16207,13,31204041,31205847,3772.0,3550.0,91.0,127.0,92.000000,99.263158,13.000000,25.4,95.631579,19.200000,76.431579,4.980811
16208,13,31255461,31256397,1235.0,1289.0,82.0,93.0,30.121951,32.500000,11.714286,18.6,31.310976,15.157143,16.153833,2.065757
16209,1,266527441,266529081,1234.0,1148.0,11.0,8.0,30.097561,32.473684,1.571429,1.6,31.285623,1.585714,29.699908,19.729672

In [32]:
df_out = df[(df["foldchange"]>2)&(df["change"]>1)]

In [33]:
col_list = ["chr", "start", "end"]
df_out.to_csv("goodk4me3.bed", columns=col_list, sep="\t", index=False, header=False)

In [32]:
df_out.to_csv?