In [2]:
import pandas as pd

In [13]:
df = pd.read_table("/public/home/jingxu/03.chip-seq/101TGEV/03.vis/03.deg_slm/random_peakReadcount.txt")
df.columns = ["chr", "start", "end", "wt-k27ac_1", "wt-k27ac_2", "wt-input_1", "wt-input_2", "pi-k27ac_1", "pi-k27ac_2", "pi-input_1", "pi-input_2"]

In [33]:
#h3k4me3_R1,h3k4me3_R2
#41,285,688 38,983,472

### normalization of sequence depth

In [14]:
df["wt-k27ac_1nor"] = df["wt-k27ac_1"]/47
df["wt-k27ac_2nor"] = df["wt-k27ac_2"]/53
df["wt-igg_1nor"] = df["wt-input_1"]/10
df["wt-igg_2nor"] = df["wt-input_2"]/10
df["pi-k27ac_1nor"] = df["pi-k27ac_1"]/38
df["pi-k27ac_2nor"] = df["pi-k27ac_2"]/59
df["pi-igg_1nor"] = df["pi-input_1"]/8
df["pi-igg_2nor"] = df["pi-input_2"]/9
df

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-input_1,pi-input_2,wt-k27ac_1nor,wt-k27ac_2nor,wt-igg_1nor,wt-igg_2nor,pi-k27ac_1nor,pi-k27ac_2nor,pi-igg_1nor,pi-igg_2nor
0,chr6,44644966,44648966,153.0,149.0,12.0,27.0,132.0,181.0,16.0,34.0,3.255319,2.811321,1.2,2.7,3.473684,3.067797,2.000,3.777778
1,chr3,26020590,26024590,1021.0,1486.0,77.0,93.0,1480.0,2217.0,42.0,36.0,21.723404,28.037736,7.7,9.3,38.947368,37.576271,5.250,4.000000
2,chr1,201870001,201874001,59.0,58.0,12.0,26.0,86.0,144.0,26.0,32.0,1.255319,1.094340,1.2,2.6,2.263158,2.440678,3.250,3.555556
3,chr5,64127179,64131179,248.0,344.0,82.0,51.0,464.0,628.0,65.0,89.0,5.276596,6.490566,8.2,5.1,12.210526,10.644068,8.125,9.888889
4,chr14,74966888,74970888,46.0,37.0,14.0,15.0,23.0,38.0,10.0,14.0,0.978723,0.698113,1.4,1.5,0.605263,0.644068,1.250,1.555556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1222,chr2,6210184,6214184,59.0,46.0,10.0,16.0,43.0,54.0,14.0,17.0,1.255319,0.867925,1.0,1.6,1.131579,0.915254,1.750,1.888889
1223,chr18,42523041,42527041,61.0,28.0,12.0,18.0,42.0,26.0,10.0,10.0,1.297872,0.528302,1.2,1.8,1.105263,0.440678,1.250,1.111111
1224,chr2,44645747,44649747,10.0,28.0,12.0,18.0,13.0,19.0,4.0,8.0,0.212766,0.528302,1.2,1.8,0.342105,0.322034,0.500,0.888889
1225,chr12,21021814,21025814,48.0,124.0,41.0,30.0,180.0,345.0,32.0,42.0,1.021277,2.339623,4.1,3.0,4.736842,5.847458,4.000,4.666667
1226,chr13,65757454,65761454,2342.0,3945.0,368.0,319.0,2852.0,4927.0,220.0,256.0,49.829787,74.433962,36.8,31.9,75.052632,83.508475,27.500,28.444444

In [15]:
def mean_of_cols(row):
        return row[["wt-k27ac_1nor","wt-k27ac_2nor"]].mean()

    

df["wt-k27ac_mean"] = df.apply(mean_of_cols, axis=1)

In [16]:
def mean_of_cols(row):
        return row[["pi-k27ac_1nor","pi-k27ac_2nor"]].mean()

    

df["pi-k27ac_mean"] = df.apply(mean_of_cols, axis=1)

In [17]:
def mean_of_cols(row):
        return row[["wt-igg_1nor","wt-igg_2nor"]].mean()

    

df["wt-igg_mean"] = df.apply(mean_of_cols, axis=1)

In [18]:
def mean_of_cols(row):
        return row[["pi-igg_1nor","pi-igg_2nor"]].mean()

    

df["pi-igg_mean"] = df.apply(mean_of_cols, axis=1)

In [19]:
df

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-input_1,...,wt-igg_1nor,wt-igg_2nor,pi-k27ac_1nor,pi-k27ac_2nor,pi-igg_1nor,pi-igg_2nor,wt-k27ac_mean,pi-k27ac_mean,wt-igg_mean,pi-igg_mean
0,chr6,44644966,44648966,153.0,149.0,12.0,27.0,132.0,181.0,16.0,...,1.2,2.7,3.473684,3.067797,2.000,3.777778,3.033320,3.270740,1.95,2.888889
1,chr3,26020590,26024590,1021.0,1486.0,77.0,93.0,1480.0,2217.0,42.0,...,7.7,9.3,38.947368,37.576271,5.250,4.000000,24.880570,38.261820,8.50,4.625000
2,chr1,201870001,201874001,59.0,58.0,12.0,26.0,86.0,144.0,26.0,...,1.2,2.6,2.263158,2.440678,3.250,3.555556,1.174829,2.351918,1.90,3.402778
3,chr5,64127179,64131179,248.0,344.0,82.0,51.0,464.0,628.0,65.0,...,8.2,5.1,12.210526,10.644068,8.125,9.888889,5.883581,11.427297,6.65,9.006944
4,chr14,74966888,74970888,46.0,37.0,14.0,15.0,23.0,38.0,10.0,...,1.4,1.5,0.605263,0.644068,1.250,1.555556,0.838418,0.624665,1.45,1.402778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1222,chr2,6210184,6214184,59.0,46.0,10.0,16.0,43.0,54.0,14.0,...,1.0,1.6,1.131579,0.915254,1.750,1.888889,1.061622,1.023417,1.30,1.819444
1223,chr18,42523041,42527041,61.0,28.0,12.0,18.0,42.0,26.0,10.0,...,1.2,1.8,1.105263,0.440678,1.250,1.111111,0.913087,0.772971,1.50,1.180556
1224,chr2,44645747,44649747,10.0,28.0,12.0,18.0,13.0,19.0,4.0,...,1.2,1.8,0.342105,0.322034,0.500,0.888889,0.370534,0.332070,1.50,0.694444
1225,chr12,21021814,21025814,48.0,124.0,41.0,30.0,180.0,345.0,32.0,...,4.1,3.0,4.736842,5.847458,4.000,4.666667,1.680450,5.292150,3.55,4.333333
1226,chr13,65757454,65761454,2342.0,3945.0,368.0,319.0,2852.0,4927.0,220.0,...,36.8,31.9,75.052632,83.508475,27.500,28.444444,62.131875,79.280553,34.35,27.972222

In [20]:
df["wt-k27ac_foldchange"] = df["wt-k27ac_mean"]/df["wt-igg_mean"]
df["pi-k27ac_foldchange"] = df["pi-k27ac_mean"]/df["pi-igg_mean"]
df

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-input_1,...,pi-k27ac_1nor,pi-k27ac_2nor,pi-igg_1nor,pi-igg_2nor,wt-k27ac_mean,pi-k27ac_mean,wt-igg_mean,pi-igg_mean,wt-k27ac_foldchange,pi-k27ac_foldchange
0,chr6,44644966,44648966,153.0,149.0,12.0,27.0,132.0,181.0,16.0,...,3.473684,3.067797,2.000,3.777778,3.033320,3.270740,1.95,2.888889,1.555549,1.132179
1,chr3,26020590,26024590,1021.0,1486.0,77.0,93.0,1480.0,2217.0,42.0,...,38.947368,37.576271,5.250,4.000000,24.880570,38.261820,8.50,4.625000,2.927126,8.272826
2,chr1,201870001,201874001,59.0,58.0,12.0,26.0,86.0,144.0,26.0,...,2.263158,2.440678,3.250,3.555556,1.174829,2.351918,1.90,3.402778,0.618331,0.691176
3,chr5,64127179,64131179,248.0,344.0,82.0,51.0,464.0,628.0,65.0,...,12.210526,10.644068,8.125,9.888889,5.883581,11.427297,6.65,9.006944,0.884749,1.268721
4,chr14,74966888,74970888,46.0,37.0,14.0,15.0,23.0,38.0,10.0,...,0.605263,0.644068,1.250,1.555556,0.838418,0.624665,1.45,1.402778,0.578220,0.445306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1222,chr2,6210184,6214184,59.0,46.0,10.0,16.0,43.0,54.0,14.0,...,1.131579,0.915254,1.750,1.888889,1.061622,1.023417,1.30,1.819444,0.816632,0.562489
1223,chr18,42523041,42527041,61.0,28.0,12.0,18.0,42.0,26.0,10.0,...,1.105263,0.440678,1.250,1.111111,0.913087,0.772971,1.50,1.180556,0.608725,0.654752
1224,chr2,44645747,44649747,10.0,28.0,12.0,18.0,13.0,19.0,4.0,...,0.342105,0.322034,0.500,0.888889,0.370534,0.332070,1.50,0.694444,0.247023,0.478180
1225,chr12,21021814,21025814,48.0,124.0,41.0,30.0,180.0,345.0,32.0,...,4.736842,5.847458,4.000,4.666667,1.680450,5.292150,3.55,4.333333,0.473366,1.221265
1226,chr13,65757454,65761454,2342.0,3945.0,368.0,319.0,2852.0,4927.0,220.0,...,75.052632,83.508475,27.500,28.444444,62.131875,79.280553,34.35,27.972222,1.808788,2.834260

In [21]:
col_list = ["wt-k27ac_foldchange", "pi-k27ac_foldchange"]
df.to_csv("random_foldchange.bed", columns=col_list, sep="\t", index=False, header=True)

In [32]:
df_out.to_csv?