In [27]:
import pandas as pd

gene = pd.read_table("/public/home/luzhang/08.TGEV/02.results/rna-seq/star_rsem/rsem.merged.gene_tpm.tsv")
gene

,gene_id,transcript_id(s),TGEV_REP1,TGEV_REP2,TGEV_REP3,WT_REP1,WT_REP2,WT_REP3
0,ENSSSCG00000000002,ENSSSCT00000000003,4.81,3.13,4.73,3.79,5.62,4.07
1,ENSSSCG00000000003,"ENSSSCT00000000004,ENSSSCT00000052628,ENSSSCT0...",2.19,2.65,3.76,1.81,2.85,4.39
2,ENSSSCG00000000005,ENSSSCT00000000006,1.60,2.28,1.48,1.03,1.08,0.86
3,ENSSSCG00000000006,ENSSSCT00000000007,0.91,1.72,1.25,0.88,1.23,1.33
4,ENSSSCG00000000007,"ENSSSCT00000000008,ENSSSCT00000057594,ENSSSCT0...",8.18,9.08,8.88,5.73,7.24,6.23
...,...,...,...,...,...,...,...,...
30472,ENSSSCG00000051794,"ENSSSCT00000029953,ENSSSCT00000037685,ENSSSCT0...",15.97,14.91,13.70,9.19,7.75,10.58
30473,ENSSSCG00000051795,ENSSSCT00000075332,0.04,0.03,0.06,1.03,0.88,1.46
30474,ENSSSCG00000051796,ENSSSCT00000083535,0.00,0.00,0.13,0.00,0.00,0.00
30475,ENSSSCG00000051797,ENSSSCT00000088271,0.00,0.00,0.00,0.00,0.04,0.00
30476,ENSSSCG00000051798,ENSSSCT00000091644,0.00,0.00,0.00,0.00,0.00,0.00

In [28]:
linkG = pd.read_table("chaLinkG.txt",header=None)
linkG.columns = ["chrom", "start", "end", "geneN", "gene_id", "strand"]
linkG

      chrom     start       end    geneN             gene_id strand
0     chr10  12755456  12757456    WDR26  ENSSSCG00000010849      -
1     chr10  12792991  12794991  ensembl  ENSSSCG00000041459      +
2     chr10  12818576  12820576    CNIH3  ENSSSCG00000034972      +
3     chr10  13046856  13048856  ensembl  ENSSSCG00000051138      +
4     chr10  13248178  13250178  ensembl  ENSSSCG00000031483      +
...     ...       ...       ...      ...                 ...    ...
6537   chrX  98024375  98026375     NKRF  ENSSSCG00000012620      -
6538   chrX  98155970  98157970   SOWAHD  ENSSSCG00000012618      +
6539   chrX  98160607  98162607  SEPTIN6  ENSSSCG00000012619      -
6540   chrX  98177918  98179918  ensembl  ENSSSCG00000019600      -
6541   chrX  98180332  98182332  ensembl  ENSSSCG00000030849      -

[6542 rows x 6 columns]

In [29]:
df_out = pd.merge(linkG, gene, on="gene_id")
df_out["TGEV_mean"] = df_out[["TGEV_REP1","TGEV_REP2","TGEV_REP3"]].mean(axis=1)
df_out["WT_mean"] = df_out[["WT_REP1","WT_REP2","WT_REP3"]].mean(axis=1)
df_final = df_out[(df_out["TGEV_mean"]>1)&(df_out["WT_mean"]>1)]
df_final

,chrom,start,end,geneN,gene_id,strand,transcript_id(s),TGEV_REP1,TGEV_REP2,TGEV_REP3,WT_REP1,WT_REP2,WT_REP3,TGEV_mean,WT_mean
0,chr10,12755456,12757456,WDR26,ENSSSCG00000010849,-,"ENSSSCT00000011871,ENSSSCT00000078473",63.06,58.86,54.99,23.30,25.76,28.69,58.970000,25.916667
4,chr10,13248178,13250178,ensembl,ENSSSCG00000031483,+,ENSSSCT00000056845,2.27,1.78,2.20,1.60,1.84,2.84,2.083333,2.093333
5,chr10,13357315,13359315,ensembl,ENSSSCG00000042067,+,ENSSSCT00000088077,2.49,3.39,3.61,2.96,3.95,4.18,3.163333,3.696667
15,chr10,16740339,16742339,AKT3,ENSSSCG00000010872,-,"ENSSSCT00000011894,ENSSSCT00000033298,ENSSSCT0...",1.77,1.87,2.42,1.19,2.23,1.80,2.020000,1.740000
17,chr10,16914501,16916501,ZBTB18,ENSSSCG00000035213,+,"ENSSSCT00000037297,ENSSSCT00000089597",7.69,7.62,7.80,4.69,4.73,5.02,7.703333,4.813333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,chrX,97924131,97926131,UBE2A,ENSSSCG00000012621,+,"ENSSSCT00000013800,ENSSSCT00000076060,ENSSSCT0...",48.84,41.18,38.92,31.15,30.84,38.44,42.980000,33.476667
6536,chrX,97985278,97987278,CXorf56,ENSSSCG00000012622,-,"ENSSSCT00000013801,ENSSSCT00000079359",33.21,29.79,24.37,21.69,24.78,17.74,29.123333,21.403333
6537,chrX,98024375,98026375,NKRF,ENSSSCG00000012620,-,"ENSSSCT00000013799,ENSSSCT00000069958",25.48,23.88,21.91,6.97,7.57,6.76,23.756667,7.100000
6539,chrX,98160607,98162607,SEPTIN6,ENSSSCG00000012619,-,"ENSSSCT00000013798,ENSSSCT00000033202,ENSSSCT0...",8.17,10.83,8.69,10.22,10.54,10.63,9.230000,10.463333
6541,chrX,98180332,98182332,ensembl,ENSSSCG00000030849,-,ENSSSCT00000035556,209.60,285.60,198.96,452.70,422.32,281.35,231.386667,385.456667

In [30]:
df_final.to_csv("TchaLinkG.txt", index=False, sep="\t")

In [31]:
df_out[df_out["geneN"] == "ANPEP"]

,chrom,start,end,geneN,gene_id,strand,transcript_id(s),TGEV_REP1,TGEV_REP2,TGEV_REP3,WT_REP1,WT_REP2,WT_REP3,TGEV_mean,WT_mean
5253,chr7,55372881,55374881,ANPEP,ENSSSCG00000001849,-,"ENSSSCT00000002072,ENSSSCT00000035626,ENSSSCT0...",2.29,2.54,2.51,1.64,2.1,3.88,2.446667,2.54