In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_table("total_compartment_histonesignal.txt",header=None)
df.columns = ["chr", "start", "end", "wt-k27ac_1", "wt-k27ac_2",'wt-4me3_1','wt-4me3_2','wt-27me3_1','wt-27me3_2', "wt-input_1", "wt-input_2", "pi-k27ac_1", "pi-k27ac_2",'pi-4me3_1','pi-4me3_2','pi-27me3_1','pi-27me3_2',"pi-input_1", "pi-input_2","Compartment"]
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,wt-input_2,pi-k27ac_1,pi-k27ac_2,pi-4me3_1,pi-4me3_2,pi-27me3_1,pi-27me3_2,pi-input_1,pi-input_2,Compartment
0,chr8,84700000,84800000,465.0,534.0,238.0,286.0,2274.0,2636.0,194.0,212.0,206.0,300.0,92.0,442.0,826.0,1424.0,216.0,207.0,a2b
1,chr6,6400000,6500000,1545.0,1647.0,425.0,462.0,1211.0,1420.0,350.0,336.0,1051.0,1594.0,151.0,663.0,326.0,720.0,326.0,364.0,a2b
2,chr7,45600000,45700000,1275.0,1100.0,332.0,397.0,494.0,485.0,324.0,266.0,639.0,803.0,78.0,401.0,95.0,178.0,254.0,296.0,a2b
3,chr2,118500000,118600000,1207.0,1069.0,276.0,280.0,912.0,1011.0,213.0,250.0,488.0,838.0,90.0,478.0,262.0,518.0,212.0,210.0,a2b
4,chr9,133000000,133100000,999.0,964.0,582.0,592.0,8446.0,9524.0,495.0,470.0,505.0,809.0,219.0,982.0,3295.0,5671.0,494.0,563.0,a2b

In [3]:
#calibrate depth
df["wt-k27ac_1nor"] = df["wt-k27ac_1"]/47
df["wt-k27ac_2nor"] = df["wt-k27ac_2"]/53
df["wt-4me3_1nor"] = df["wt-4me3_1"]/37
df["wt-4me3_2nor"] = df["wt-4me3_2"]/34
df["wt-k27me3_1nor"] = df["wt-27me3_1"]/63
df["wt-k27me3_2nor"] = df["wt-27me3_2"]/73
df["wt-igg_1nor"] = df["wt-input_1"]/10
df["wt-igg_2nor"] = df["wt-input_2"]/10
df["pi-k27ac_1nor"] = df["pi-k27ac_1"]/38
df["pi-k27ac_2nor"] = df["pi-k27ac_2"]/59
df["pi-4me3_1nor"] = df["pi-4me3_1"]/13
df["pi-4me3_2nor"] = df["pi-4me3_2"]/58
df["pi-k27me3_1nor"] = df["pi-27me3_1"]/26
df["pi-k27me3_2nor"] = df["pi-27me3_2"]/46
df["pi-igg_1nor"] = df["pi-input_1"]/8
df["pi-igg_2nor"] = df["pi-input_2"]/9
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,...,wt-igg_1nor,wt-igg_2nor,pi-k27ac_1nor,pi-k27ac_2nor,pi-4me3_1nor,pi-4me3_2nor,pi-k27me3_1nor,pi-k27me3_2nor,pi-igg_1nor,pi-igg_2nor
0,chr8,84700000,84800000,465.0,534.0,238.0,286.0,2274.0,2636.0,194.0,...,19.4,21.2,5.421053,5.084746,7.076923,7.620690,31.769231,30.956522,27.00,23.000000
1,chr6,6400000,6500000,1545.0,1647.0,425.0,462.0,1211.0,1420.0,350.0,...,35.0,33.6,27.657895,27.016949,11.615385,11.431034,12.538462,15.652174,40.75,40.444444
2,chr7,45600000,45700000,1275.0,1100.0,332.0,397.0,494.0,485.0,324.0,...,32.4,26.6,16.815789,13.610169,6.000000,6.913793,3.653846,3.869565,31.75,32.888889
3,chr2,118500000,118600000,1207.0,1069.0,276.0,280.0,912.0,1011.0,213.0,...,21.3,25.0,12.842105,14.203390,6.923077,8.241379,10.076923,11.260870,26.50,23.333333
4,chr9,133000000,133100000,999.0,964.0,582.0,592.0,8446.0,9524.0,495.0,...,49.5,47.0,13.289474,13.711864,16.846154,16.931034,126.730769,123.282609,61.75,62.555556

In [4]:
df['wt-k27ac_mean'] = df[['wt-k27ac_1nor', 'wt-k27ac_2nor']].mean(axis=1)
df['wt-4me3_mean'] = df[['wt-4me3_1nor', 'wt-4me3_2nor']].mean(axis=1)
df['wt-k27me3_mean'] = df[['wt-k27me3_1nor', 'wt-k27me3_2nor']].mean(axis=1)
df['wt-igg_mean'] = df[['wt-igg_1nor', 'wt-igg_2nor']].mean(axis=1)

In [5]:
df['pi-k27ac_mean'] = df[['pi-k27ac_1nor', 'pi-k27ac_2nor']].mean(axis=1)
df['pi-4me3_mean'] = df[['pi-4me3_1nor', 'pi-4me3_2nor']].mean(axis=1)
df['pi-k27me3_mean'] = df[['pi-k27me3_1nor', 'pi-k27me3_2nor']].mean(axis=1)
df['pi-igg_mean'] = df[['pi-igg_1nor', 'pi-igg_2nor']].mean(axis=1)

In [6]:
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,...,pi-igg_1nor,pi-igg_2nor,wt-k27ac_mean,wt-4me3_mean,wt-k27me3_mean,wt-igg_mean,pi-k27ac_mean,pi-4me3_mean,pi-k27me3_mean,pi-igg_mean
0,chr8,84700000,84800000,465.0,534.0,238.0,286.0,2274.0,2636.0,194.0,...,27.00,23.000000,9.984544,7.422099,36.102414,20.30,5.252899,7.348806,31.362876,25.000000
1,chr6,6400000,6500000,1545.0,1647.0,425.0,462.0,1211.0,1420.0,350.0,...,40.75,40.444444,31.973906,12.537361,19.337139,34.30,27.337422,11.523210,14.095318,40.597222
2,chr7,45600000,45700000,1275.0,1100.0,332.0,397.0,494.0,485.0,324.0,...,31.75,32.888889,23.941188,10.324722,7.242553,29.50,15.212979,6.456897,3.761706,32.319444
3,chr2,118500000,118600000,1207.0,1069.0,276.0,280.0,912.0,1011.0,213.0,...,26.50,23.333333,22.925331,7.847377,14.162753,23.15,13.522748,7.582228,10.668896,24.916667
4,chr9,133000000,133100000,999.0,964.0,582.0,592.0,8446.0,9524.0,495.0,...,61.75,62.555556,19.721999,16.570747,132.264623,48.25,13.500669,16.888594,125.006689,62.152778

In [8]:
df["wt-k27ac_change"] = np.log2((df["wt-k27ac_mean"] + 1e-3)/(df["wt-igg_mean"] + 1e-3))
df["wt-4me3_change"] = np.log2((df["wt-4me3_mean"] + 1e-3)/(df["wt-igg_mean"] + 1e-3))
df["wt-k27me3_change"] = np.log2((df["wt-k27me3_mean"] + 1e-3)/(df["wt-igg_mean"] + 1e-3))
df["pi-k27ac_change"] = np.log2((df["pi-k27ac_mean"] + 1e-3)/(df["pi-igg_mean"] + 1e-3))
df["pi-4me3_change"] = np.log2((df["pi-4me3_mean"] + 1e-3)/(df["pi-igg_mean"] + 1e-3))
df["pi-k27me3_change"] = np.log2((df["pi-k27me3_mean"] + 1e-3)/(df["pi-igg_mean"] + 1e-3))
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,...,pi-k27ac_mean,pi-4me3_mean,pi-k27me3_mean,pi-igg_mean,wt-k27ac_change,wt-4me3_change,wt-k27me3_change,pi-k27ac_change,pi-4me3_change,pi-k27me3_change
0,chr8,84700000,84800000,465.0,534.0,238.0,286.0,2274.0,2636.0,194.0,...,5.252899,7.348806,31.362876,25.000000,-1.023638,-1.451457,0.830584,-2.250525,-1.766208,0.327118
1,chr6,6400000,6500000,1545.0,1647.0,425.0,462.0,1211.0,1420.0,350.0,...,27.337422,11.523210,14.095318,40.597222,-0.101311,-1.451902,-0.826802,-0.570487,-1.816749,-1.526098
2,chr7,45600000,45700000,1275.0,1100.0,332.0,397.0,494.0,485.0,324.0,...,15.212979,6.456897,3.761706,32.319444,-0.301209,-1.514521,-2.025994,-1.087049,-2.323311,-3.102605
3,chr2,118500000,118600000,1207.0,1069.0,276.0,280.0,912.0,1011.0,213.0,...,13.522748,7.582228,10.668896,24.916667,-0.014069,-1.560608,-0.708871,-0.881674,-1.716285,-1.223623
4,chr9,133000000,133100000,999.0,964.0,582.0,592.0,8446.0,9524.0,495.0,...,13.500669,16.888594,125.006689,62.152778,-1.290680,-1.541833,1.454807,-2.202704,-1.879707,1.008103

In [9]:
df.loc[df['wt-k27ac_change'] < 0, 'wt-k27ac_change'] = 0
df.loc[df['wt-4me3_change'] < 0, 'wt-4me3_change'] = 0
df.loc[df['wt-k27me3_change'] < 0, 'wt-k27me3_change'] = 0
df.loc[df['pi-k27ac_change'] < 0, 'pi-k27ac_change'] = 0
df.loc[df['pi-4me3_change'] < 0, 'pi-4me3_change'] = 0
df.loc[df['pi-k27me3_change'] < 0, 'pi-k27me3_change'] = 0
df.head()

,chr,start,end,wt-k27ac_1,wt-k27ac_2,wt-4me3_1,wt-4me3_2,wt-27me3_1,wt-27me3_2,wt-input_1,...,pi-k27ac_mean,pi-4me3_mean,pi-k27me3_mean,pi-igg_mean,wt-k27ac_change,wt-4me3_change,wt-k27me3_change,pi-k27ac_change,pi-4me3_change,pi-k27me3_change
0,chr8,84700000,84800000,465.0,534.0,238.0,286.0,2274.0,2636.0,194.0,...,5.252899,7.348806,31.362876,25.000000,0.0,0.0,0.830584,0.0,0.0,0.327118
1,chr6,6400000,6500000,1545.0,1647.0,425.0,462.0,1211.0,1420.0,350.0,...,27.337422,11.523210,14.095318,40.597222,0.0,0.0,0.000000,0.0,0.0,0.000000
2,chr7,45600000,45700000,1275.0,1100.0,332.0,397.0,494.0,485.0,324.0,...,15.212979,6.456897,3.761706,32.319444,0.0,0.0,0.000000,0.0,0.0,0.000000
3,chr2,118500000,118600000,1207.0,1069.0,276.0,280.0,912.0,1011.0,213.0,...,13.522748,7.582228,10.668896,24.916667,0.0,0.0,0.000000,0.0,0.0,0.000000
4,chr9,133000000,133100000,999.0,964.0,582.0,592.0,8446.0,9524.0,495.0,...,13.500669,16.888594,125.006689,62.152778,0.0,0.0,1.454807,0.0,0.0,1.008103

In [10]:
h3k27ac = df[["chr","start","end","wt-k27ac_change","pi-k27ac_change","Compartment"]] 
h3k27ac.head()
h3k27ac.to_csv("h3k27ac_change.txt", sep="\t", index=False)

In [11]:
h3k27me3 = df[["chr","start","end","wt-k27me3_change","pi-k27me3_change","Compartment"]] 
h3k27me3.head()
h3k27me3.to_csv("h3k27me3_change.txt", sep="\t", index=False)

In [12]:
h3k4me3 = df[["chr","start","end","wt-4me3_change","pi-4me3_change","Compartment"]] 
h3k4me3.head()
h3k4me3.to_csv("h3k4me3_change.txt", sep="\t", index=False)